### ISSUE TITLE
"Failed to spawn command processing-java"

### ISSUE THREAD

**Issue by hjrmorais** [bleikamp/processing#17]
First of all thanks for creating this!

I'm running on **OSX El Capitan** with **Processing 3** and **Atom 1.2.1** but cannot get this package to work.

Every time I hit ctrl-alt-b this pops up:
 >Failed to spawn command `processing-java`. Make sure `processing-java` is installed and on your PATH 

Also checked */usr/local/bin/* and processing-java is there.

Any one having the same issue?

**Comment by mdgriest** [comment]
Yes, exactly the same, actually! I am wondering if this release works with Processing 2 but not 3 yet.

**Comment by jslvtr** [comment]
Go into the package in Atom and check the Settings section. It should have a `Processing-executable` section.

Go into your terminal and type `which processing-java`. The output of that, put in the field mentioned above (e.g. `usr/local/bin/processing-java`).

Then, close Atom.

Go into your terminal and type `atom`.

I also had a couple problems running it initially, but it certainly works with Processing 3, and on OS X El Capitan.

**Comment by zlot** [comment]
Thanks @jslvtr, didn't realise there was a `Processing-executable` setting for the package. Forcing the path here fixed it for me. Cheers

**Comment by jslvtr** [comment]
No problem--might be a bug in the package.

**Comment by mdgriest** [comment]
Sorry if this should be simple but I am not sure how to locate the `Processing-executable`. When I open my `Packages` menu, the only Processing option is Run. Any thoughts?
![screen shot 2015-11-19 at 7 57 17 am](https://cloud.githubusercontent.com/assets/11529706/11272578/8d76cc76-8e93-11e5-8594-7e5da4260af9.png)

**Comment by hjrmorais** [comment]
Thanks @jslvtr !!!

**Comment by jslvtr** [comment]
@mdgriest Open your settings with `CMD+,`, then, click on `Packages`. Then, search for `processing`. Click on the `processing` package. Enter the output of `which processing-java` (which you've ran in Terminal) in the field as mentioned above.

@hjrmorais no worries!

**Comment by mdgriest** [comment]
@jslvtr That did the trick. Thank you so much for taking the time to spell it out for me. I really appreciate your help!

**Comment by jslvtr** [comment]
@mdgriest no worries, glad you got it sorted!

**Comment by davemacdo** [comment]
Sorry, but I'm having the same problem as @mdgriest, but I do not see any setting's the the package card. 

![screen shot 2016-01-19 at 10 44 49 pm](https://cloud.githubusercontent.com/assets/6425544/12439405/49e27f1e-befe-11e5-86cc-336c4b40e125.png)

What am I missing? I have verified that processing-java is in /usr/local/bin/

**Comment by pingoklooi** [comment]
I tried jslvtr's steps (added the result of 'which processing-java' to the Processing-executable field but got a '/usr/local/bin/processing-java: line 13: /Applications/Processing: No such file or directory' error. Anyone know what's wrong? Am also running atom from command line.

**Comment by jslvtr** [comment]
@pingoklooi Processing should be in the folder /Applications, but it is not.
Could you move the Processing executable into the /Applications folder?

This folder is inside Macintosh HD.

**Comment by pingoklooi** [comment]
My processing folder is named 'Processing 2' (it already is under the applications folder), so I renamed it to 'Processing', but got this error instead '/usr/local/bin/processing-java: line 13: cd: /Applications/Processing 2.app/Contents/Java: No such file or directory'. 

Where can I set the processing folder to the default 'Processing 2'? Is that the cause of this error? Cheers

**Comment by jslvtr** [comment]
The problem would _seem_ to be the space between Processing and 2, although not really sure why.
Sorry I can't be of more help!
