### ISSUE TITLE
Add install instruction for linux users

### ISSUE THREAD

**Issue by theArchonius** [bleikamp/processing#2]
The steps described in section "Running a sketch from Atom" does not work on linux systems as the menu entry "Install `processing-java`" is not available in current processing versions for linux.
However, the same can be easily achieved by adding `processing-java` to your executable search path. This can be done by adding the processing directory to your `PATH` environment variable or by adding a symlink to any existing directory within your `PATH`. I'd suggest adding a symlink to `/usr/local/bin` as it is usually already in your `PATH`:

```bash
sudo ln -s /path/to/processing/processing-java /usr/local/bin/
```

if `sudo` is not installed or the operation is not allowed, switch to a user that has write permissions to `/usr/local/bin` and run the command without `sudo` (or ask someone other with write permissions to do it):

```bash
ln -s /path/to/processing/processing-java /usr/local/bin/
```

This should work on most Linux distributions, so I'd suggest adding these notes to the README file for your package.

**Comment by bleikamp** [comment]
@theArchonius Any interest in opening up a Pull Request with the instructions? I'd be happy to merge it.
