### ISSUE TITLE
Can't run sketches (Mac OS X El Capitan)

### ISSUE THREAD

**Issue by r00ben** [bleikamp/processing#21]
Atom 1.3.2
Processing Package 0.11.0
Mac OS X El Capitan 10.11.2

**"processing-java"** has been installed but I always get the following error message when I try to run my sketch:
"Failed to spawn command processing-java. Make sure processing-java is installed and on your PATH"

Sublime Text 3 runs my sketches smoothly without any problems but I would prefer to use Atom for Processing too.

**Comment by bleikamp** [comment]
> "Failed to spawn command processing-java. Make sure processing-java is installed and on your PATH"

Have you checked to make sure `processing-java` is on your `$PATH`?

**Comment by federico-pepe** [comment]
@r00ben had the same issue. Then installed [atom-build](https://atom.io/packages/build) package and now it works fine.

**Comment by paolocamerin** [comment]
@bleikamp  Hi! I have the same problem. How can I check if processing-java is in my $PATH ?

**Comment by bleikamp** [comment]
1. From the command line run `which processing`.
1. From the command line, run `echo $PATH`.
1. If you don't see the path from `which processing` in your `$PATH`, you can add it by typing: `PATH="$PATH:[your processing path]` on the command line.
