### ISSUE TITLE
Passing the wrong filename

### ISSUE THREAD

**Issue by davemacdo** [bleikamp/processing#24]
After installing the build package, I am a little closer to getting Processing to run my sketch. However, it processing-java seems to be receiving the wrong filename. My folder is called test.pde and is on my Desktop (Mac OS X El Capitan), but when I try to build the file, I get an error telling me that 

`.../Desktop/Desktop.pde does not exist.`

It seems like it's trying to process a file that has a different name than the one I'm trying to send it.

**Comment by bleikamp** [comment]
@davemacdo This issue is old, but you should make a folder called `test` and a file in it called `test.pde` on your desktop.
