### ISSUE TITLE
Cannot Close/Resize Error Window

### ISSUE THREAD

**Issue by samendez** [bleikamp/processing#31]
There doesn't seem to be a way to close error windows, even clicking the little red X in the bottom right doesn't get rid of it. 
It seems as though that section of the screen is the console, and while that makes sense it should be resizable and closable, and, as of right now it has a default max size and has an ugly overlap with the editor display (as seen in the screenshot below)

![image](https://cloud.githubusercontent.com/assets/7675767/17040250/4ec634de-4f64-11e6-869e-07aa1621fb25.png)

**Comment by JamesHagerman** [comment]
I just noticed this as well.

**Comment by samendez** [comment]
There's a great plugin for atom called script that lets you run all sorts of languages. I recently added processing language functionality. Check it out.

**Comment by JamesHagerman** [comment]
For anyone else that shows up here, there is a keyboard shortcut for closing the sketch:

```
'ctrl-alt-b': 'processing:run'
'ctrl-alt-c': 'processing:close'
```

Closing the sketch using this keyboard shortcut will also close the Processing window...

**Comment by heavydetail** [comment]
its annoying, please provide an alternate way to close this panel, like all the other panels.
(may I suggest an x?)
thank you.

**Comment by bleikamp** [comment]
Unlikely to be fixed by me
