### ISSUE TITLE
Can't get it working on Windows 7

### ISSUE THREAD

**Issue by svcnt** [bleikamp/processing#7]
I installed Processing langage and Processing packages for Atom 1.0, made the modifications suggested by chrsmlls333 but still can't run my sketches. No error messages, just nothing happens. The same sketches runs without problems in Sublime Text 3, so it's not the system. 

Any ideas?

Thank you

**Comment by chrsmlls333** [comment]
Open the developer console and check for error messages there.

**Comment by sbryant** [comment]
@svcnt try with the latest changes please and as @chrsmlls333 asked, are there any messages in the developer console?

**Comment by svcnt** [comment]
Thanks for your answer.

I upgraded both packages and still it does not work. This is the error message I get:

""processing-java" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable (TRANSLATION: ... is not recognized as a command, program or batch file).
C:\Users\Jose Vicente\.atom\packages\processing\lib\processing.coffee:53 
stderr
C:\Users\Jose Vicente\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:85 
(anonymous function)
events.js:77 
emitOne
events.js:166 
emit
_stream_readable.js:146 
readableAddChunk
_stream_readable.js:109 
Readable.push
net.js:517 
onread
C:\Users\Jose Vicente\.atom\packages\processing\lib\processing.coffee:56 

Error code: 1

**Comment by sbryant** [comment]
@svcnt that means your processing executable is not in your path. 

Checkout https://github.com/bleikamp/processing/pull/8#issuecomment-116122762 for an example of how to get processing working without setting up your path.

**Comment by svcnt** [comment]
Done!
Thanks a lot for your work and your help!!
